cbass:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "cbass"
  freq_ghz: 4.76
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.03

spass:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "spass"
  freq_ghz: 2.3
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.03

wham:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "wham"
  freq_ghz: null
  unit: "R"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I"]
  calerr: null

planck353_pr3:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "planck353_pr3"
  freq_ghz: 353.0
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"   # <- if you converted from COSMO during preprocessing
  calerr: 0.01

planck217_pr3:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "planck217_pr3"
  freq_ghz: 217.0
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.01

planck143_pr3:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "planck143_pr3"
  freq_ghz: 143.0
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.01

planck100_pr3:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "planck100_pr3"
  freq_ghz: 100.0
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.01

planck070_cosmo:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "planck070_cosmo"
  freq_ghz: 70.4
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.01

planck044_cosmo:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "planck044_cosmo"
  freq_ghz: 44.1
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.01

planck030_cosmo:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "planck030_cosmo"
  freq_ghz: 28.4
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.01

wmapK_cosmo:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "wmapK_cosmo"
  freq_ghz: 22.5
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.01

wmapKa_cosmo:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "wmapKa_cosmo"
  freq_ghz: 33.0
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.01

wmapQ1_cosmo:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "wmapQ1_cosmo"
  freq_ghz: 40.7
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.01

wmapQ2_cosmo:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "wmapQ2_cosmo"
  freq_ghz: 40.7
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.01

wmapV1_cosmo:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "wmapV1_cosmo"
  freq_ghz: 60.8
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.01

wmapV2_cosmo:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "wmapV2_cosmo"
  freq_ghz: 60.8
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.01

wmapW1_cosmo:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "wmapW1_cosmo"
  freq_ghz: 93.5
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.01

wmapW2_cosmo:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "wmapW2_cosmo"
  freq_ghz: 93.5
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.01

wmapW3_cosmo:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "wmapW3_cosmo"
  freq_ghz: 93.5
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.01

wmapW4_cosmo:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "wmapW4_cosmo"
  freq_ghz: 93.5
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.01

# Optional derived dataset entry (once you generate it)
cbass_spass:
  source: "products/processed_maps/v001/processed_maps.h5"
  group: "cbass_spass"
  freq_ghz: 4.76
  unit: "K_RJ"
  fwhm_arcmin: 60.0
  nside: 16
  coord: "G"
  stokes: ["I","Q","U"]
  pol_convention: "COSMO"
  calerr: 0.03

litebird_LFT_L1-040:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_LFT_L1-040_var_IQU_nside016.fits
  freq_ghz: 40.0
  fwhm_arcmin: 70.5
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_LFT_L2-050:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_LFT_L2-050_var_IQU_nside016.fits
  freq_ghz: 50.0
  fwhm_arcmin: 58.5
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_LFT_L1-060:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_LFT_L1-060_var_IQU_nside016.fits
  freq_ghz: 60.0
  fwhm_arcmin: 51.1
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_LFT_L3-068:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_LFT_L3-068_var_IQU_nside016.fits
  freq_ghz: 68.0
  fwhm_arcmin: 41.6
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_LFT_L2-068:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_LFT_L2-068_var_IQU_nside016.fits
  freq_ghz: 68.0
  fwhm_arcmin: 47.1
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_LFT_L4-078:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_LFT_L4-078_var_IQU_nside016.fits
  freq_ghz: 78.0
  fwhm_arcmin: 36.9
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_LFT_L1-078:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_LFT_L1-078_var_IQU_nside016.fits
  freq_ghz: 78.0
  fwhm_arcmin: 43.8
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_LFT_L3-089:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_LFT_L3-089_var_IQU_nside016.fits
  freq_ghz: 89.0
  fwhm_arcmin: 33.0
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_LFT_L2-089:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_LFT_L2-089_var_IQU_nside016.fits
  freq_ghz: 89.0
  fwhm_arcmin: 41.5
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_LFT_L4-100:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_LFT_L4-100_var_IQU_nside016.fits
  freq_ghz: 100.0
  fwhm_arcmin: 30.2
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_LFT_L3-119:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_LFT_L3-119_var_IQU_nside016.fits
  freq_ghz: 119.0
  fwhm_arcmin: 26.3
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_LFT_L4-140:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_LFT_L4-140_var_IQU_nside016.fits
  freq_ghz: 140.0
  fwhm_arcmin: 23.7
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_MFT_M1-100:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_MFT_M1-100_var_IQU_nside016.fits
  freq_ghz: 100.0
  fwhm_arcmin: 37.8
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_MFT_M2-119:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_MFT_M2-119_var_IQU_nside016.fits
  freq_ghz: 119.0
  fwhm_arcmin: 33.6
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_MFT_M1-140:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_MFT_M1-140_var_IQU_nside016.fits
  freq_ghz: 140.0
  fwhm_arcmin: 30.8
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_MFT_M2-166:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_MFT_M2-166_var_IQU_nside016.fits
  freq_ghz: 166.0
  fwhm_arcmin: 28.9
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_MFT_M1-195:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_MFT_M1-195_var_IQU_nside016.fits
  freq_ghz: 195.0
  fwhm_arcmin: 28.0
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_HFT_H1-195:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_HFT_H1-195_var_IQU_nside016.fits
  freq_ghz: 195.0
  fwhm_arcmin: 28.6
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_HFT_H2-235:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_HFT_H2-235_var_IQU_nside016.fits
  freq_ghz: 235.0
  fwhm_arcmin: 24.7
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_HFT_H1-280:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_HFT_H1-280_var_IQU_nside016.fits
  freq_ghz: 280.0
  fwhm_arcmin: 22.5
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_HFT_H2-337:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_HFT_H2-337_var_IQU_nside016.fits
  freq_ghz: 337.0
  fwhm_arcmin: 20.9
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
litebird_HFT_H3-402:
  filename: data/litebird_hitmaps/maps_ptep_ns0016/LiteBIRD_HFT_H3-402_var_IQU_nside016.fits
  freq_ghz: 402.0
  fwhm_arcmin: 17.9
  read_class: LiteBIRDSimPTEPReader
  coord: G
  unit: K_RJ
  stokes:
  - I
  - Q
  - U
  pol_convention: COSMO
  calerr: 0.01
